spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentification_bdd
    username: postgres
    password: user123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: authentification
  config:
    import: optional:configserver:http://localhost:8888
mail:
  host: smtp.gmail.com
  port: 587
  username: "oumaymaabdennadher72@gmail.com"
  password: "hdeh gmog bmss xhbu"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
         enabled: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000
application:
   security:
     jwt:
       secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
       expiration: 8640000
   mailing:
     frontend:
       activation-url: http://localhost:4200/activate-account

server:
    port: 8088
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




